# Generated by Django 4.2.5 on 2023-11-16 17:24

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("blogpages", "0003_remove_blogdetail_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogdetail",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("text", wagtail.blocks.TextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
