# Generated by Django 4.2.5 on 2023-11-20 21:47

from django.db import migrations
import wagtail.blocks
import wagtail.blocks.static_block
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("blogpages", "0006_author_alter_blogdetail_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogdetail",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "info",
                        wagtail.blocks.static_block.StaticBlock(
                            admin_text="This is a content divider with extra information."
                        ),
                    ),
                    (
                        "faq",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    ("question", wagtail.blocks.CharBlock()),
                                    (
                                        "answer",
                                        wagtail.blocks.RichTextBlock(
                                            features=["bold", "italic"]
                                        ),
                                    ),
                                ]
                            ),
                            label="Frequently Asked Questions",
                            max_num=5,
                            min_num=1,
                        ),
                    ),
                    ("text", wagtail.blocks.TextBlock()),
                    (
                        "carousel",
                        wagtail.blocks.StreamBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "quotation",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("text", wagtail.blocks.TextBlock()),
                                            ("author", wagtail.blocks.TextBlock()),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    ("doc", wagtail.documents.blocks.DocumentChooserBlock()),
                    (
                        "page",
                        wagtail.blocks.PageChooserBlock(
                            page_type=["home.HomePage"], required=False
                        ),
                    ),
                    (
                        "author",
                        wagtail.snippets.blocks.SnippetChooserBlock("blogpages.Author"),
                    ),
                    (
                        "call_to_action_1",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=["bold", "italic"], required=True
                                    ),
                                ),
                                ("page", wagtail.blocks.PageChooserBlock()),
                                (
                                    "button_text",
                                    wagtail.blocks.CharBlock(
                                        max_length=100, required=False
                                    ),
                                ),
                            ],
                            label="CTA #1",
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
