# Generated by Django 4.2.5 on 2023-11-22 18:43

import blocks.blocks
from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("blogpages", "0007_alter_blogdetail_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogdetail",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("info", blocks.blocks.InfoBlock()),
                    ("faq", blocks.blocks.FAQListBlock()),
                    ("text", blocks.blocks.TextBlock()),
                    (
                        "carousel",
                        wagtail.blocks.StreamBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "quotation",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("text", wagtail.blocks.TextBlock()),
                                            ("author", wagtail.blocks.TextBlock()),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("image", blocks.blocks.ImageBlock()),
                    (
                        "doc",
                        wagtail.documents.blocks.DocumentChooserBlock(
                            group="Standalone blocks"
                        ),
                    ),
                    (
                        "page",
                        wagtail.blocks.PageChooserBlock(
                            group="Standalone blocks",
                            page_type=["home.HomePage"],
                            required=False,
                        ),
                    ),
                    (
                        "author",
                        wagtail.snippets.blocks.SnippetChooserBlock("blogpages.Author"),
                    ),
                    (
                        "call_to_action_1",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=["bold", "italic"], required=True
                                    ),
                                ),
                                ("page", wagtail.blocks.PageChooserBlock()),
                                (
                                    "button_text",
                                    wagtail.blocks.CharBlock(
                                        max_length=100, required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
