# Generated by Django 4.2.5 on 2023-12-10 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blogpages", "0009_author_expire_at_author_expired_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogdetail",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="blogpages.author",
            ),
        ),
    ]
