# Generated by Django 5.0 on 2023-12-14 21:41

import blocks.blocks
import django.db.models.deletion
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogpages", "0012_alter_author_options"),
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogdetail",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="images.customimage",
            ),
        ),
        migrations.AddField(
            model_name="blogdetail",
            name="intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="blogdetail",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("info", blocks.blocks.InfoBlock()),
                    ("faq", blocks.blocks.FAQListBlock()),
                    ("text", blocks.blocks.TextBlock()),
                    (
                        "carousel",
                        wagtail.blocks.StreamBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                (
                                    "quotation",
                                    wagtail.blocks.StructBlock(
                                        [
                                            ("text", wagtail.blocks.TextBlock()),
                                            ("author", wagtail.blocks.TextBlock()),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("image", blocks.blocks.ImageBlock()),
                    (
                        "doc",
                        wagtail.documents.blocks.DocumentChooserBlock(
                            group="Standalone blocks"
                        ),
                    ),
                    ("page", blocks.blocks.CustomPageChooserBlock()),
                    (
                        "author",
                        wagtail.snippets.blocks.SnippetChooserBlock("blogpages.Author"),
                    ),
                    (
                        "call_to_action_1",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.RichTextBlock(
                                        features=["bold", "italic"], required=True
                                    ),
                                ),
                                ("page", wagtail.blocks.PageChooserBlock()),
                                (
                                    "button_text",
                                    wagtail.blocks.CharBlock(
                                        max_length=100, required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
