# Generated by Django 5.0 on 2023-12-18 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogpages", "0013_blogdetail_image_blogdetail_intro_and_more"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="locale",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="translation_key",
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
