# Generated by Django 5.0 on 2023-12-18 18:17

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel

class Migration(migrations.Migration):
    dependencies = [
        ("blogpages", "0014_author_locale_author_translation_key"),
    ]

    operations = [
        BootstrapTranslatableModel('blogpages.Author'),
    ]
