# Generated by Django 4.2.5 on 2023-09-26 17:25

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_homepage_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
