# Generated by Django 4.2.5 on 2023-10-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        ("home", "0005_homepage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="custom_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.customdocument",
            ),
        ),
    ]
