# Generated by Django 4.2.5 on 2023-10-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_homepage_cta_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="cta_external_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
