# Generated by Django 4.2.5 on 2023-12-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_homepagegalleryimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagegalleryimage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
